; Listing generated by Microsoft (R) Optimizing Compiler Version 19.34.31937.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	f
PUBLIC	main
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	fiboasm:PROC
EXTRN	atoi:PROC
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN3
	DD	imagerel $LN3+67
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN3
	DD	imagerel $LN3+87
	DD	imagerel $unwind$printf
pdata	ENDS
pdata	SEGMENT
$pdata$f DD	imagerel $LN5
	DD	imagerel $LN5+85
	DD	imagerel $unwind$f
$pdata$main DD	imagerel $LN5
	DD	imagerel $LN5+108
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG9876	DB	'ccc=%d => %d', 0aH, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$f DD	010801H
	DD	06208H
$unwind$main DD	010d01H
	DD	0620dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 011801H
	DD	06218H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 011801H
	DD	06218H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 32
fx3$ = 36
argc$ = 64
argv$ = 72
main	PROC
; File C:\Users\matsp\Documents\virtualbox-share\fibo64\fibo.c
; Line 23
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 24
	mov	DWORD PTR a$[rsp], 0
; Line 27
	cmp	DWORD PTR argc$[rsp], 2
	jne	SHORT $LN2@main
; Line 28
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR argv$[rsp]
	mov	rcx, QWORD PTR [rcx+rax]
	call	atoi
	mov	DWORD PTR a$[rsp], eax
	jmp	SHORT $LN3@main
$LN2@main:
; Line 30
	mov	DWORD PTR a$[rsp], 1
$LN3@main:
; Line 42
	mov	ecx, 3
	call	fiboasm
	mov	DWORD PTR fx3$[rsp], eax
; Line 43
	mov	r8d, DWORD PTR fx3$[rsp]
	mov	edx, 3
	lea	rcx, OFFSET FLAT:$SG9876
	call	printf
; Line 51
	xor	eax, eax
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
retval$ = 32
x2$1 = 36
x1$2 = 40
x$ = 64
f	PROC
; File C:\Users\matsp\Documents\virtualbox-share\fibo64\fibo.c
; Line 6
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 9
	cmp	DWORD PTR x$[rsp], 1
	jg	SHORT $LN2@f
; Line 10
	mov	eax, DWORD PTR x$[rsp]
	mov	DWORD PTR retval$[rsp], eax
; Line 11
	jmp	SHORT $LN3@f
$LN2@f:
; Line 13
	mov	eax, DWORD PTR x$[rsp]
	dec	eax
	mov	ecx, eax
	call	f
	mov	DWORD PTR x1$2[rsp], eax
; Line 14
	mov	eax, DWORD PTR x$[rsp]
	sub	eax, 2
	mov	ecx, eax
	call	f
	mov	DWORD PTR x2$1[rsp], eax
; Line 15
	mov	eax, DWORD PTR x2$1[rsp]
	mov	ecx, DWORD PTR x1$2[rsp]
	add	ecx, eax
	mov	eax, ecx
	mov	DWORD PTR retval$[rsp], eax
$LN3@f:
; Line 19
	mov	eax, DWORD PTR retval$[rsp]
; Line 20
	add	rsp, 56					; 00000038H
	ret	0
f	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT printf
_TEXT	SEGMENT
_Result$ = 32
_ArgList$ = 40
_Format$ = 64
printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\stdio.h
; Line 956
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 56					; 00000038H
; Line 959
	lea	rax, QWORD PTR _Format$[rsp+8]
	mov	QWORD PTR _ArgList$[rsp], rax
; Line 960
	mov	ecx, 1
	call	__acrt_iob_func
	mov	r9, QWORD PTR _ArgList$[rsp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR _Format$[rsp]
	mov	rcx, rax
	call	_vfprintf_l
	mov	DWORD PTR _Result$[rsp], eax
; Line 961
	mov	QWORD PTR _ArgList$[rsp], 0
; Line 962
	mov	eax, DWORD PTR _Result$[rsp]
; Line 963
	add	rsp, 56					; 00000038H
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\stdio.h
; Line 644
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 645
	call	__local_stdio_printf_options
	mov	rcx, QWORD PTR _ArgList$[rsp]
	mov	QWORD PTR [rsp+32], rcx
	mov	r9, QWORD PTR _Locale$[rsp]
	mov	r8, QWORD PTR _Format$[rsp]
	mov	rdx, QWORD PTR _Stream$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf
; Line 646
	add	rsp, 56					; 00000038H
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_stdio_config.h
; Line 92
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
